apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get_accesskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get_accesskey
  template:
    metadata:
      labels:
        app: get_accesskey
    spec:
      containers:
      - name: get_accesskey
        image: ggamdi/agent:v1
      env:
      - name: DAYS
        value: 30
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws
            key: AWS_SECRET_ACCESS_KEY

