apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-test
  template:
    metadata:
      labels:
        app: sre-test
    spec:
      containers:
      - name: sre-test
        image: ggamdi/sre-test:v1
        imagePullPolicy: Always
        env:
        - name: DAYS
          value: "1000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: sre-test-svc
spec:
  selector:
    app: sre-test
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080